var edad = 18
//edad = edad + 1
edad += 1
var peso = 70
peso -= 2
var sandiwich = 5
peso += sandiwich
var jugar = 0.5
peso -= jugar
var precioDeVino = 200.141526
var total = Math.round(precioDeVino *100*3)/100
var totalstr = total.toFixed(4)
var total2 = parseFloat(totalstr)
var pizza = 10*10
var persona = 2
var qppl = pizza / persona // cantidad pizza persona
